# Generated by Django 2.1.7 on 2019-03-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlscore',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
